# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fcffcb8e71b724de6afa083b3fadfd18"
name = "ph-test checkout extension"
handle = "ph-test-checkout-extension"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "ph-test-muhammad.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
